[package]
name = "abi"
version = "0.1.0"
license = "MIT"
edition = "2024"

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
tonic = "0.13.1"

[build-dependencies]
tonic-build = "0.13.1"
